FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
ARG REACT_APP_API_BASE_URL=http://localhost:8080
ARG REACT_APP_WS_URL=http://localhost:8086/ws
ARG REACT_APP_NOTIFICATIONS_WS_URL=http://localhost:8087/ws
ENV REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL
ENV REACT_APP_WS_URL=$REACT_APP_WS_URL
ENV REACT_APP_NOTIFICATIONS_WS_URL=$REACT_APP_NOTIFICATIONS_WS_URL
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
