global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'config-server'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['config-server:8888']

  - job_name: 'eureka-server'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['eureka-server:8761']

  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'auth-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['auth-service:8081']

  - job_name: 'user-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['user-service:8082']

  - job_name: 'startup-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['startup-service:8083']

  - job_name: 'investment-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['investment-service:8084']

  - job_name: 'team-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['team-service:8085']

  - job_name: 'messaging-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['messaging-service:8086']

  - job_name: 'notification-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['notification-service:8087']

  - job_name: 'payment-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['payment-service:8089']
