package com.capgemini.notification.enums;

public enum NotificationType {
    USER_REGISTERED,
    STARTUP_CREATED,
    STARTUP_REJECTED,
    INVESTMENT_CREATED,
    INVESTMENT_APPROVED,
    INVESTMENT_REJECTED,
    TEAM_INVITE_SENT,
    PAYMENT_SUCCESS,
    PAYMENT_REJECTED
}
