spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**
              filters:
                - name: JwtAuthenticationFilter

            - id: startup-service
              uri: lb://STARTUP-SERVICE
              predicates:
                - Path=/startups/**
              filters:
                - name: JwtAuthenticationFilter

            - id: investment-service
              uri: lb://INVESTMENT-SERVICE
              predicates:
                - Path=/investments/**
              filters:
                - name: JwtAuthenticationFilter

            - id: team-service
              uri: lb://TEAM-SERVICE
              predicates:
                - Path=/teams/**
              filters:
                - name: JwtAuthenticationFilter

            - id: messaging-service
              uri: lb://MESSAGING-SERVICE
              predicates:
                - Path=/messages/**
              filters:
                - name: JwtAuthenticationFilter

            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/notifications/**
              filters:
                - name: JwtAuthenticationFilter

            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/payments/**
              filters:
                - name: JwtAuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    com.capgemini.apigateway: INFO

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
